version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    ports:
      - 5432:5432

  worker:
    build: ./worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SENDGRID_FROM_EMAIL=rishabhmthakur2@gmail.com
      - SENDGRID_API_KEY=***
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db:5432/users
    volumes:
      - ./worker/worker.py:/app/worker.py
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: ./app
    volumes:
      - ./worker/worker.py:/app/worker.py
    ports:
      - 5050:5050
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SENDGRID_FROM_EMAIL=rishabhmthakur2@gmail.com
      - SENDGRID_API_KEY=***
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db:5432/users
    depends_on:
      - db
      - redis
      - worker
  job_viewer:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - redis
