version: "3.7"
services:
  db:
    image: postgres:latest
    volumes: 
     - postgres-volume:/var/lib/postgresql/data
     - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quote-db 
  quote-service:
    build: ./quote-service/
    image: quote-service-image
    ports:
      - "5050:5000"
volumes:
  postgres-volume: {}
  