version: "3.7"
services:
  db:
    image: postgres:latest
    volumes: 
     - postgres-volume:/var/lib/postgresql/data
     - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data-warehouse 
  api:
    build: ./api/
    image: api-image
    ports:
      - "5050:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/data-warehouse
volumes:
  postgres-volume: {}
  